sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
# cache: npm
cache:
  directories:
    - node_modules
branches:
  only:
    - main # build master branch only

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  # - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
  target_branch: gh-pages
